name: Build Check

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

# Cancel in-progress runs when a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Type Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript type checking
        run: npm run type-check

      - name: Build Next.js application
        env:
          # Provide minimal env vars needed for build
          NEXT_PUBLIC_TURNSTILE_SITE_KEY: ${{ secrets.NEXT_PUBLIC_TURNSTILE_SITE_KEY || 'dummy-key-for-build' }}
          DATABASE_URL: ${{ secrets.DATABASE_URL || 'postgresql://dummy:dummy@localhost/dummy' }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY || 'dummy-groq-key' }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY || 'dummy-anthropic-key' }}
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY || 'dummy-elevenlabs-key' }}
          JWT_SECRET: ${{ secrets.JWT_SECRET || 'dummy-jwt-secret' }}
          TURNSTILE_SECRET_KEY: ${{ secrets.TURNSTILE_SECRET_KEY || 'dummy-turnstile-secret' }}
          # Sentry is optional for builds
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN || '' }}
        run: npm run build

      - name: Check for build output
        run: |
          if [ ! -d ".next" ]; then
            echo "Build failed: .next directory not found"
            exit 1
          fi
          echo "Build successful!"

      # Optional: Upload build artifacts for debugging
      - name: Upload build artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            .next/build-manifest.json
            .next/trace
          retention-days: 3

  # Optional: Run tests if they exist
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build  # Only run tests if build passes
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test || echo "No tests configured"
        continue-on-error: true  # Don't fail if no tests exist yet